### PR TITLE
use favicons

### PR DESCRIPTION
**Pull request by jacekkopecky**
addresses #45, it works for me 8-)

probably also needs the following:
* [ ] remove icons files
* [ ] maybe consolidate icons.css into a different file? what's that `.gryf`?

### CODE REVIEW

**Comment by ear1grey** [comment]
Thanks @jacekkopecky :-)

**Comment by jacekkopecky** [comment]
cheers, should we address the two extra tasks?
- remove icons files
- maybe consolidate icons.css into a different file? what's that .gryf?

**Comment by ear1grey** [comment]
Those are in hand.

**Comment by jacekkopecky** [comment]
also add 
```
.favicon {
  width: 16px;
  height: 16px;
}
```
so it doesn't visibly reflow as the icons get loaded

**Comment by ear1grey** [comment]
That's in already, with a flex-shrink: 0.

**Comment by jacekkopecky** [comment]
nope; since the code doesn't put width and height in the favicon img tags, and CSS doesn't specify size either, the browser gives the image no space until it loads it – for me it loads visibly and because space is tight, the extra 16px add visible reflow to the opening of the new tab

**Pull request merged**
